# Generated by Django 4.1.4 on 2022-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Match Name')),
                ('site_name', models.CharField(max_length=150)),
                ('first_image', models.ImageField(upload_to='teams/%y/%m/%d')),
                ('second_image', models.ImageField(upload_to='teams/%y/%m/%d')),
                ('price', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=1000)),
                ('channel', models.CharField(max_length=40)),
                ('commentary', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Match Slug (URL)')),
                ('file', models.CharField(max_length=1500)),
            ],
        ),
    ]
