# Generated by Django 4.1.4 on 2022-12-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_site_channel_remove_site_commentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='file',
        ),
    ]
