# Generated by Django 4.1.4 on 2022-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_site_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Site Naame'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=150, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Site Slug (URL)'),
        ),
    ]
