# Generated by Django 4.1.4 on 2022-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_site_name_alter_site_site_name_alter_site_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='first_image',
            field=models.ImageField(upload_to='sites/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='site',
            name='second_image',
            field=models.ImageField(upload_to='sites/%y/%m/%d'),
        ),
    ]
