# Generated by Django 4.1.4 on 2022-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_site_site_name_site_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_name',
            field=models.CharField(default=1, max_length=40, verbose_name='Site Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name For Slug'),
        ),
    ]
