# Generated by Django 4.1.4 on 2022-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_site_site_name_alter_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_name',
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Site Name'),
        ),
    ]
