# Generated by Django 4.1.4 on 2022-12-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_site_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='price',
            new_name='friday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='desc',
        ),
        migrations.AddField(
            model_name='site',
            name='contact_name',
            field=models.CharField(default=1, max_length=1000, verbose_name='Contact Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='contact_url',
            field=models.CharField(default=1, max_length=1000, verbose_name='Contact Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(default=1, max_length=1000, verbose_name='Site Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='duration',
            field=models.CharField(default=1, max_length=1000, verbose_name='Recomended Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='higher_price',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='lower_price',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='map_url',
            field=models.CharField(default=1, max_length=1000, verbose_name='Map Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='monday_close',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='monday_open',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='open_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='saturday_close',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='saturday_open',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='sunday_close',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='sunday_open',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='third_image',
            field=models.ImageField(default=1, upload_to='sites/%y/%m/%d', verbose_name='Third Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='thursday_close',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='thursday_open',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='tuesday_close',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='tuesday_open',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='wednesday_close',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='wednesday_open',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='first_image',
            field=models.ImageField(upload_to='sites/%y/%m/%d', verbose_name='First Image (Main)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='second_image',
            field=models.ImageField(upload_to='sites/%y/%m/%d', verbose_name='Second Image'),
        ),
    ]
