# Generated by Django 4.1.4 on 2022-12-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_site_fourth_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='Fourth_image',
            new_name='fourth_image',
        ),
    ]
