# Generated by Django 4.1.4 on 2022-12-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_site_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='contact_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Contact Url'),
        ),
        migrations.AlterField(
            model_name='site',
            name='map_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Map Url'),
        ),
    ]
