# Generated by Django 4.1.4 on 2022-12-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_site_contact_url_alter_site_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='friday_open',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
    ]
