# Generated by Django 4.1.4 on 2022-12-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_site_friday_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='open_hours',
            field=models.CharField(max_length=100),
        ),
    ]
