# Generated by Django 4.1.4 on 2022-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_site_higher_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
