# Generated by Django 4.1.4 on 2022-12-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_site_close_hours_alter_site_friday_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='contact',
            field=models.CharField(choices=[('THERE IS', 'There Is Contact'), ('THERE ISNT', 'There Isnt Contact')], default='THERE ISNT', max_length=20),
        ),
    ]
