# Generated by Django 4.1.4 on 2022-12-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_site_close_hours_alter_site_friday_close_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='map_url',
        ),
        migrations.AddField(
            model_name='site',
            name='map',
            field=models.CharField(choices=[('THERE IS', 'There Is MAP Link'), ('THERE ISNT', 'There Isnt MAP Link')], default='THERE ISNT', max_length=200, verbose_name='There Is Contact?'),
        ),
        migrations.AddField(
            model_name='site',
            name='map_link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Map Link URL'),
        ),
    ]
