# Generated by Django 4.1.4 on 2022-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_site_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userw', models.CharField(max_length=40)),
                ('passw', models.CharField(max_length=40)),
            ],
        ),
    ]
