# Generated by Django 4.1.4 on 2022-12-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_site_first_image_alter_site_fourth_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='first_image',
            field=models.ImageField(default='default/default.jpg', upload_to='sites/%y/%m/%d', verbose_name='First Image (Main)'),
        ),
    ]
