# Generated by Django 4.1.4 on 2022-12-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_site_friday_close_remove_site_friday_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='rate',
            field=models.IntegerField(default='5'),
        ),
    ]
