# Generated by Django 4.1.4 on 2022-12-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_site_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='first_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
