# Generated by Django 4.1.4 on 2022-12-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_delete_newsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='arabic_name',
            field=models.CharField(default=1, max_length=40, verbose_name='Arabic Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=40, verbose_name='English Name'),
        ),
    ]
