# Generated by Django 4.1.4 on 2022-12-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='site',
            name='commentary',
        ),
    ]
