# Generated by Django 4.1.4 on 2022-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_site_contact_name_alter_site_friday_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='friday_close',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='monday_close',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='monday_open',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='saturday_close',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='saturday_open',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='sunday_close',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='sunday_open',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='thursday_close',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='thursday_open',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='tuesday_close',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='tuesday_open',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='wednesday_close',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='wednesday_open',
            field=models.CharField(blank=True, default='1', max_length=30),
        ),
    ]
