# Generated by Django 4.1.4 on 2022-12-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_site_friday_close_alter_site_monday_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
