# Generated by Django 4.1.4 on 2022-12-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_site_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='hours',
            field=models.CharField(choices=[('SAME', 'Same Hours All The Week'), ('NOT_SAME', 'There Is Open Hour But Not Same'), ('NO', 'There Isnt Hours Availble')], default='SAME', max_length=20, verbose_name='There Is Open Hours?'),
        ),
        migrations.AddField(
            model_name='site',
            name='money',
            field=models.CharField(choices=[('THERE IS', 'There Is Money'), ('THERE ISNT', 'There Isnt Money')], default='THERE ISNT', max_length=20, verbose_name='There Is Money Needed?'),
        ),
        migrations.AlterField(
            model_name='site',
            name='close_hours',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('', '4'), ('', '5'), ('', '6'), ('', '7'), ('', '8'), ('', '9'), ('', '10'), ('', '11'), ('', '12')], max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='contact',
            field=models.CharField(choices=[('THERE IS', 'There Is Contact'), ('THERE ISNT', 'There Isnt Contact')], default='THERE ISNT', max_length=20, verbose_name='There Is Contact?'),
        ),
        migrations.AlterField(
            model_name='site',
            name='higher_price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Higher Price'),
        ),
        migrations.AlterField(
            model_name='site',
            name='lower_price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Lower Price'),
        ),
        migrations.AlterField(
            model_name='site',
            name='open_hours',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('', '4'), ('', '5'), ('', '6'), ('', '7'), ('', '8'), ('', '9'), ('', '10'), ('', '11'), ('', '12')], max_length=100),
        ),
    ]
