# Generated by Django 4.1.4 on 2022-12-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_site_map_url_site_map_site_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='map',
            field=models.CharField(choices=[('THERE IS', 'There Is MAP Link'), ('THERE ISNT', 'There Isnt MAP Link')], default='THERE IS', max_length=200, verbose_name='There Is MAP Link?'),
        ),
    ]
