# Generated by Django 4.1.4 on 2022-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_site_first_image_alter_site_fourth_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='friday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='friday_open',
        ),
        migrations.RemoveField(
            model_name='site',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='site',
            name='monday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='monday_open',
        ),
        migrations.RemoveField(
            model_name='site',
            name='saturday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='saturday_open',
        ),
        migrations.RemoveField(
            model_name='site',
            name='sunday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='sunday_open',
        ),
        migrations.RemoveField(
            model_name='site',
            name='thursday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='thursday_open',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tuesday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tuesday_open',
        ),
        migrations.RemoveField(
            model_name='site',
            name='wednesday_close',
        ),
        migrations.RemoveField(
            model_name='site',
            name='wednesday_open',
        ),
        migrations.AlterField(
            model_name='site',
            name='close_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='open_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
