# Generated by Django 4.1.4 on 2022-12-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_site_first_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='sites/%y/%m/%d', verbose_name='First Image (Main)'),
        ),
    ]
