# Generated by Django 4.1.4 on 2022-12-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_site_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSite',
        ),
    ]
