# Generated by Django 4.1.4 on 2022-12-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_price_site_friday_close_remove_site_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='Fourth_image',
            field=models.ImageField(default=1, upload_to='sites/%y/%m/%d', verbose_name='Fourth Image'),
            preserve_default=False,
        ),
    ]
