# Generated by Django 4.1.4 on 2022-12-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_fourth_image_site_fourth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='contact_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='friday_close',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='monday_close',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='monday_open',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='saturday_close',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='saturday_open',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='sunday_close',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='sunday_open',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='thursday_close',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='thursday_open',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='tuesday_close',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='tuesday_open',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='wednesday_close',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='wednesday_open',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
