# Generated by Django 4.1.4 on 2022-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_site_open_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='close_hours',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
