# Generated by Django 4.1.4 on 2022-12-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_newsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsite',
            old_name='passw',
            new_name='passwords',
        ),
        migrations.RenameField(
            model_name='newsite',
            old_name='userw',
            new_name='username',
        ),
    ]
